=== Guns-229/Let-s-explore-Python/Section 2 - Advance Python/Chapter S2.03 - JSON/code/2schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Welcome",
    "definitions": {
        "Welcome": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "project_id": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "cluster_name_prefix": {
                    "type": "string"
                },
                "cluster_name": {
                    "type": "string"
                },
                "cluster_labels_selector": {
                    "$ref": "#/definitions/ClusterLabelsSelector"
                },
                "cluster_workflow_labels_selector": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "exclude_workflow_templates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "replication_policies": {
                    "$ref": "#/definitions/ReplicationPolicies"
                }
            },
            "required": [],
            "title": "Welcome"
        },
        "ClusterLabelsSelector": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "azy": {
                    "type": "string"
                },
                "azy2": {
                    "type": "string"
                }
            },
            "required": [],
            "title": "ClusterLabelsSelector"
        },
        "ReplicationPolicies": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "aggressive_downscaling": {
                    "type": "string"
                },
                "aggressive_upscaling": {
                    "type": "string"
                },
                "bau": {
                    "type": "string"
                }
            },
            "required": [],
            "title": "ReplicationPolicies"
        }
    }
}

=== Guns-229/Let-s-explore-Python/Section 2 - Advance Python/Chapter S2.03 - JSON/code/1data.json
{
"project_id": "db-data-factory",
"region": "asia-south1",
"cluster_name_prefix": "dprocutil-default",
"cluster_name": "some-cluster-name",
"cluster_labels_selector": {
"azy": "pyspark-stream-example",
"azy2": "cluster_selector-default"
},
"cluster_workflow_labels_selector": [
"azy",
"selector_key1"
],
"exclude_workflow_templates": [
"poc-template"
],
"replication_policies": {
"aggressive_downscaling": "azy-downscaling_asia-south1",
"aggressive_upscaling": "azy-upscaling_asia-south1",
"bau": "azy-bau_asia-south1"
}
}
